

CREATE TABLE ALMACEN (NUMERO_ALMACEN INTEGER,UBICACION_ALAMCEN VARCHAR2(40),
                        CONSTRAINT PK_NA PRIMARY KEY(NUMERO_ALMACEN));

--PROCEDIMIENTO GUARDAR_ALAMACEN

CREATE OR REPLACE PROCEDURE GUARDAR_ALMACEN(MY_NUMERO_ALMACEN IN INTEGER,
MY_UBICACION_ALMACEN IN VERACRUZ)

AS
BEGIN
INSERT INTO ALMACEN VALUES(MY_NUMERO_ALMACEN, MY_UBICACION_ALMACEN);
END;
/

--EFECTUAMOS UN SELECT PARA VERIFICAR QUE SE GUARDO UN ALMACEN

SELECT * FROM ALMACEN;



CREATE TABLE CLIENTE (NUMERO_CLIENTE INTEGER , NUMERO_ALMACEN INTEGER, NOMBRE_CLIENTE VARCHAR2(80),
                      CONSTRAINT PK_N_C PRIMARY KEY (NUMERO_CLIENTE),
                      CONSTRAINT FK1_N_A FOREIGN KEY (NUMERO_ALMACEN) references ALMACEN(NUMERO_ALMACEN));
                      
   SELECT * FROM CLIENTE;       
   
   
CREATE TABLE VENDEDOR (NUMERO_VENDEDOR INTEGER, NOMBRE_VENDEDOR VARCHAR2(80),
              CONSTRAINT PK_N_V PRIMARY KEY (NUMERO_VENDEDOR));
              
    SELECT * FROM VENDEDOR;
    
CREATE TABLE VENTAS (ID_VENTAS INTEGER, NUMERO_CLIENTE INTEGER, NUMERO_VENDEDOR INTEGER, MONTO_VENTA FLOAT,
                    CONSTRAINT PK_ID_V PRIMARY KEY (ID_VENTAS),
                    CONSTRAINT FK1_N_CL FOREIGN KEY (NUMERO_CLIENTE) REFERENCES CLIENTE(NUMERO_CLIENTE),
                    CONSTRAINT FK1_N_VEN FOREIGN KEY(NUMERO_VENDEDOR) REFERENCES VENDEDOR (NUMERO_VENDEDOR));
                    
    SELECT * FROM VENTAS;
    


--EJEMPLO DE UNA TABLA Y SU PROCEDIMIENTO ALMACENADO PARA GUARDARLA CON 
-- PRIMARY KEY IMPUESTO O ARTIFICIAL

CREATE TABLE CALIFICACIONES(ID_CALIFICACION INTEGER,MATERIA VARCHAR2(80),VALOR FLOAT,
CONSTRAINT PK_ID_CAL PRIMARY KEY(ID_CALIFICACION));

--GENERAMOS UNA SECUENCIA
CREATE SEQUENCE SEC_CALIFICACIONES
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

--AQUI YA VIENE EL PROCEDIMIENTO!!!!!!!!!!!!!!!!!!
CREATE OR REPLACE PROCEDURE GUARDAR_CALIFICACIONES(
MY_ID_CALIFICACION OUT integer, MY_MATERIA IN VARCHAR2,MY_VALOR IN FLOAT
)
AS
BEGIN
SELECT SEC_CALIFICACIONES.NEXTVAL INTO MY_ID_CALIFICACION FROM DUAL;
INSERT INTO CALIFICACIONES VALUES(MY_ID_CALIFICACION,MY_MATERIA, MY_VALOR);
END;
/

--probar el procedimiento
DECLARE
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR, 'IA', 8);
END;
/

--VERIFICAMOS
SELECT * FROM CALIFICACIONES; --RELACIONADO A UN CURSOR EXPLICITO
DELETE FROM CALIFICACIONES WHERE ID_CALIFICACION=3;

SELECT * FROM CALIFICACIONES;
SELECT COUNT (*) FROM CALIFICACIONES;-- RELACIONADO A UN CURSOR IMPLICITO

DECLARE
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR, 'BD2', 7);
END;
/

SELECT * FROM CALIFICACIONES;

---EJEMPLO DE CURSOR EXPLICITO CON LA TABLA CALIFICACIONES
DECLARE
CURSOR CUR_CALIF IS SELECT * FROM CALIFICACIONES;
BEGIN
FOR REC IN CUR_CALIF LOOP
DBMS_OUTPUT.PUT_LINE('CALIFICACION ' || REC.VALOR|| ' MATERIA ' || REC.MATERIA);
END LOOP;
END;
 /
 
SET SERVEROUTPUT ON;