

CREATE TABLE ALMACEN (NUMERO_ALMACEN INTEGER,UBICACION_ALAMCEN VARCHAR2(40),
                        CONSTRAINT PK_NA PRIMARY KEY(NUMERO_ALMACEN));

--PROCEDIMIENTO GUARDAR_ALAMACEN

CREATE  OR REPALCE PROCEDURE GUARDAR_ALMACEN(MY_NUMERO_ALMACEN IN INTEGER,
MY_UBICACION_ALMACEN IN VERACRUZ)

AS
BEGIN
INSERT INTO ALMACEN VALUES(MY_NUMERO_ALMACEN, MY_UBICACION_ALMACEN);
END;
/

--EFECTUAMOS UN SELECT PARA VERIFICAR QUE SE GUARDO UN ALMACEN

SELECT * FROM ALMACEN;